--create procedures to insert, update or delete on the tables

--1-Customer's table

CREATE OR REPLACE PROCEDURE INSERT_CUST
(P_NATIONAL_ID CUSTOMER.NATIONAL_ID%TYPE, P_FIRST_NAME CUSTOMER.FIRST_NAME%TYPE,P_LAST_NAME CUSTOMER.LAST_NAME %TYPE,P_PHONE_NUMBER CUSTOMER.PHONE_NUMBER%TYPE
,P_BIRTHDATE CUSTOMER.BIRTHDATE%TYPE,P_GENDER CUSTOMER.GENDER%TYPE,P_ADDRESS CUSTOMER.ADDRESS%TYPE,P_RES_ID CUSTOMER.RESERVATION_ID %TYPE)
IS

BEGIN
INSERT INTO CUSTOMER(NATIONAL_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,BIRTHDATE,GENDER,ADDRESS,RESERVATION_ID)
 VALUES

(P_NATIONAL_ID,P_FIRST_NAME,P_LAST_NAME,P_PHONE_NUMBER,P_BIRTHDATE,P_GENDER,P_ADDRESS,P_RES_ID);

COMMIT;

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);
END;

CREATE OR REPLACE PROCEDURE DELETE_CUST(P_NATIONAL_ID IN CUSTOMER.NATIONAL_ID%TYPE)
IS
BEGIN
DELETE FROM CUSTOMER
WHERE NATIONAL_ID = P_NATIONAL_ID;

COMMIT;

EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);

END;

---------------------------------------------------------

--Region's table



CREATE OR REPLACE PROCEDURE INSERT_REGION
(P_REGION_ID REGION.REGION_ID %TYPE,P_REGION_NAME REGION.REGION_NAME %TYPE)
IS
BEGIN

INSERT INTO REGION VALUES
(P_REGION_ID,P_REGION_NAME);

COMMIT;

EXCEPTION 
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);

END;


CREATE OR REPLACE PROCEDURE DELETE_REGION(P_REGION_ID REGION.REGION_ID%TYPE)
IS
BEGIN
DELETE FROM REGION
WHERE REGION_ID = P_REGION_ID;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);

END;


---------------------------------------------------------

--Country 
SELECT * FROM COUNTRY;

CREATE OR REPLACE PROCEDURE INSERT_COUNTRY
(P_COUNTRY_ID COUNTRY.COUNTRY_ID %TYPE,P_COUNTRY_NAME COUNTRY.COUNTRY_NAME %TYPE,P_REGION_ID COUNTRY.REGION_ID%TYPE)
IS
BEGIN

INSERT INTO COUNTRY VALUES
(P_COUNTRY_ID,P_COUNTRY_NAME,P_REGION_ID);

COMMIT;

EXCEPTION 
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);

END;

CREATE OR REPLACE PROCEDURE DELETE_COUNTRY(P_COUNTRY_ID COUNTRY.COUNTRY_ID%TYPE)
IS
BEGIN
DELETE FROM COUNTRY
WHERE COUNTRY_ID = P_COUNTRY_ID;
COMMIT;
EXCEPTION
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLCODE);

END;

----------------------------------------------
--Reservation's table

CREATE OR REPLACE PROCEDURE INSERT_RES(P_RESERVATION_ID NUMBER,P_CHECK_IN DATE,P_CHECK_OUT DATE,P_ROOM_ID NUMBER,P_RESERVATION_DATE DATE, P_ROOM_PRICE NUMBER,
P_TOTAL_COST NUMBER, P_BREAKFAST_OPTION VARCHAR2,P_SEA_OPTION VARCHAR2)

IS 
BEGIN

INSERT INTO RESERVATION VALUES (P_RESERVATION_ID,P_CHECK_IN,P_CHECK_OUT,P_ROOM_ID,P_RESERVATION_DATE,P_ROOM_PRICE,P_TOTAL_COST,P_BREAKFAST_OPTION,P_SEA_OPTION);


END;


CREATE OR REPLACE PROCEDURE DELETE_RES(P_RESERVATION_ID NUMBER)
IS
BEGIN

DELETE FROM RESERVATION
WHERE RESERVATION_ID = P_RESERVATION_ID;
END;



----------------------------------------------

--Room's table
SELECT * FROM ROOM;
CREATE OR REPLACE PROCEDURE INSERT_ROOM(P_ROOM_ID NUMBER,P_ROOM_TYPE VARCHAR2,P_NUMBER_OF_BEDS NUMBER,P_OCCUPIED VARCHAR2, P_HOTEL_ID NUMBER)
IS

BEGIN

INSERT INTO ROOM VALUES(P_ROOM_ID,P_ROOM_TYPE,P_NUMBER_OF_BEDS,P_OCCUPIED,P_HOTEL_ID);

END;


CREATE OR REPLACE PROCEDURE DELETE_RES (P_ROOM_ID NUMBER)
IS
BEGIN

DELETE FROM ROOM
WHERE ROOM_ID = P_ROOM_ID;
END;










