
--Create a database job to find the total cost for each reservation 

CREATE OR REPLACE PROCEDURE UPDATE_TOTAL_COST_JOB
IS
BEGIN

UPDATE RESERVATION A
SET TOTAL_COST = ROOM_PRICE + (SELECT SUM(SER.PRICE)
FROM SER_RES SR,
SERVICE SER,
RESERVATION RES
WHERE SR.SERVICE_ID = SER.SERVICE_ID
AND RES.RESERVATION_ID = SR.RESERVATION_ID
AND TRUNC(SYSDATE) = RES.CHECK_OUT
AND RES.RESERVATION_ID = A.RESERVATION_ID--(SELECT RESERVATION_ID FROM RESERVATION WHERE TOTAL_COST IS NULL)
)

WHERE TRUNC(SYSDATE) = CHECK_OUT;

END;


BEGIN
UPDATE_TOTAL_COST_JOB;
END;




--to schedule the procedure above, follow the instructions

BEGIN 

DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'MY_JOB_FINAL',
JOB_TYPE => 'STORED_PROCEDURE',
JOB_ACTION =>'UPDATE_TOTAL_COST_JOB',
START_DATE => '06/SEP/2022 03:11:00 PM ',
repeat_interval => 'FREQ = DAILY;INTERVAL = 1',
END_DATE => '10/SEP/2022 07:00:00 PM',
AUTO_DROP => FALSE,
COMMENTS => 'My new job'
);

END;

--to drop the job
BEGIN
  dbms_scheduler.drop_job(JOB_NAME => 'MY_JOB_FINAL');
END;

-- to enable the job
begin

DBMS_SCHEDULER.ENABLE('MY_JOB_FINAL');

end;



COMMIT;







