
--Database Tables
DROP TABLE CUSTOMER;
DROP TABLE RESERVATION;
DROP TABLE ROOM;
DROP TABLE HOTEL;
DROP TABLE LOCATION;
DROP TABLE COUNTRY;
DROP TABLE REGION;
DROP TABLE SERVICE;
DROP TABLE SER_RES;




CREATE TABLE CUSTOMER
(
CUSTOMER_ID NUMBER CONSTRAINT PK_C PRIMARY KEY,
NATIONAL_ID NUMBER,
FIRST_NAME VARCHAR2(100) NOT NULL,
LAST_NAME VARCHAR2(100) NOT NULL,
PHONE_NUMBER NUMBER,
BIRTHDATE DATE,
GENDER CHAR(1) CONSTRAINT CH_CUST CHECK (GENDER IN ('M','F')),
ADDRESS VARCHAR2(100)

);

CREATE TABLE SERVICE
(
SERVICE_ID NUMBER CONSTRAINT PK_SER PRIMARY KEY,
SERVICE_TYPE VARCHAR2(10) ,
SERVICE_NAME VARCHAR2(20),
OPENING_TIME VARCHAR2(10),
CLOSING_TIME VARCHAR2(10),
PRICE NUMBER,
PERSONAL_TRAINER VARCHAR2(10) CONSTRAINT CH_PER CHECK (PERSONAL_TRAINER IN ('Yes','No')),
LOCKER VARCHAR2(10) CONSTRAINT CH_LOCK CHECK (LOCKER IN ('Yes','No'))
);

CREATE TABLE SER_RES
(
RESERVATION_ID NUMBER,
SERVICE_ID NUMBER,
CONSTRAINT PK_RES_SER PRIMARY KEY (SERVICE_ID,RESERVATION_ID),
CONSTRAINT FK_S1 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);

CREATE TABLE RESERVATION
(
RESERVATION_ID NUMBER CONSTRAINT PK_RES PRIMARY KEY,
CHECK_IN DATE NOT NULL,
CHECK_OUT DATE NOT NULL,
ROOM_ID NUMBER NOT NULL,
RESERVATION_DATE DATE,
ROOM_PRICE NUMBER,
TOTAL_COST NUMBER,
BREAKFAST_OPTION VARCHAR2(10),
SEA_OPTION VARCHAR2(10),
CUSTOMER_ID NUMBER,
CONSTRAINT FK_ROOM_ID FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ROOM_ID),
CONSTRAINT FK_FINAL FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE ROOM
(
ROOM_ID NUMBER CONSTRAINT PK_ROOM PRIMARY KEY,
ROOM_TYPE VARCHAR2(100) CONSTRAINT CH_ROOM CHECK(ROOM_TYPE IN ('Single','Double','Family')),
NUMBER_OF_BEDS NUMBER NOT NULL,
OCCUPIED VARCHAR2(20) CONSTRAINT CH_OCC CHECK(OCCUPIED IN ('Yes','No')),
HOTEL_ID NUMBER,
CONSTRAINT FK_3 FOREIGN KEY(HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)

);

CREATE TABLE HOTEL
(
HOTEL_ID NUMBER CONSTRAINT PK_HOTEL PRIMARY KEY,
HOTEL_NAME VARCHAR2(100),
PHONE_NUMBER NUMBER,
LOCATION_ID NUMBER,
CONSTRAINT FK_2 FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
);

CREATE TABLE LOCATION
(
LOCATION_ID NUMBER CONSTRAINT PK_LOCATION PRIMARY KEY,
STREET_ADDRESS VARCHAR2(40),
POSTAL_CODE VARCHAR2(12),
CITY VARCHAR2(30),
STATE_PROVINCE VARCHAR2(25),
COUNTRY_ID VARCHAR2(20),
CONSTRAINT FK_1 FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE TABLE COUNTRY
(
COUNTRY_ID VARCHAR2(10) CONSTRAINT PK_COUNTRY PRIMARY KEY,
COUNTRY_NAME VARCHAR2(40),
REGION_ID NUMBER,
CONSTRAINT FK FOREIGN KEY(REGION_ID) REFERENCES REGION(REGION_ID)
);

CREATE TABLE REGION
(
REGION_ID NUMBER CONSTRAINT PK_REGION PRIMARY KEY,
REGION_NAME VARCHAR2(50)
);






